### ISSUE TITLE
Error: error TS6053: File './elements/choose-file/choose-file.ts' not found.

### ISSUE THREAD

**Issue by ToddG** [Microtome/microtome#10]
Forget to check in a file?

[(master)]$ gulp serve
[15:12:58] Using gulpfile /.../gulpfile.js
[15:12:58] Starting 'typescript'...
[15:12:58] Starting 'styles'...
[15:12:58] Starting 'elements'...
[15:12:58] Starting 'images'...
[15:12:58] Finished 'styles' after 601 ms
[15:12:58] Finished 'elements' after 281 ms
[15:12:59] gulp-imagemin: Minified 5 images (saved 963 B - 3.8%)
[15:12:59] images all files 24.13 kB
[15:12:59] Finished 'images' after 946 ms
error TS6053: File './elements/choose-file/choose-file.ts' not found.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: error TS6053: File './elements/choose-file/choose-file.ts' not found.

[(master)]$ grep choose-file.ts \* -R
app/tsconfig.json:    "./elements/choose-file/choose-file.ts",

**Comment by ToddG** [comment]
BTW - Attempted to get around this by removing choose-file.ts from the tsconfig.json, but this led to other errors...

diff --git a/app/tsconfig.json b/app/tsconfig.json
index 8fe8b81..6aa04d2 100644
--- a/app/tsconfig.json
+++ b/app/tsconfig.json
@@ -29,7 +29,6 @@
     "./../local_typings/chrome_serial.d.ts",
     "./../local_typings/threejs-extended.d.ts",
     "./../bower_components/polymer-ts/polymer-ts.d.ts",
-    "./elements/choose-file/choose-file.ts",
   "./elements/fab-menu/fab-menu.ts",
   "./elements/fab-radial/fab-radial.ts",
   "./elements/layer-height/layer-height.ts",

[(master)]$ gulp serve
[15:17:12] Using gulpfile /.../gulpfile.js
[15:17:12] Starting 'typescript'...
[15:17:12] Starting 'styles'...
[15:17:12] Starting 'elements'...
[15:17:12] Starting 'images'...
[15:17:12] Finished 'styles' after 626 ms
[15:17:12] Finished 'elements' after 291 ms
[15:17:13] gulp-imagemin: Minified 5 images (saved 963 B - 3.8%)
[15:17:13] images all files 24.13 kB
[15:17:13] Finished 'images' after 965 ms
app/elements/layer-height/layer-height.ts(30,28): error TS2304: Cannot find name 'PaperRadioGroup'.
app/elements/layer-height/layer-height.ts(32,26): error TS2304: Cannot find name 'PaperInput'.
app/elements/layer-height/layer-height.ts(35,53): error TS2304: Cannot find name 'PaperRadioGroup'.
app/elements/layer-height/layer-height.ts(36,54): error TS2304: Cannot find name 'PaperInput'.

**Comment by DanielJoyce** [comment]
Those should be okay to ignore and the server should still boot.

On Fri, Mar 25, 2016, 15:22 Todd Greenwood-Geer notifications@github.com
wrote:

> BTW - Attempted to get around this by removing choose-file.ts from the
> tsconfig.json, but this led to other errors...
> 
> diff --git a/app/tsconfig.json b/app/tsconfig.json
> index 8fe8b81..6aa04d2 100644
> --- a/app/tsconfig.json
> +++ b/app/tsconfig.json
> @@ -29,7 +29,6 @@
> "./../local_typings/chrome_serial.d.ts",
> "./../local_typings/threejs-extended.d.ts",
> "./../bower_components/polymer-ts/polymer-ts.d.ts",
> - "./elements/choose-file/choose-file.ts",
>   "./elements/fab-menu/fab-menu.ts", "./elements/fab-radial/fab-radial.ts",
>   "./elements/layer-height/layer-height.ts",
> 
> [(master)]$ gulp serve
> [15:17:12] Using gulpfile /.../gulpfile.js
> [15:17:12] Starting 'typescript'...
> [15:17:12] Starting 'styles'...
> [15:17:12] Starting 'elements'...
> [15:17:12] Starting 'images'...
> [15:17:12] Finished 'styles' after 626 ms
> [15:17:12] Finished 'elements' after 291 ms
> [15:17:13] gulp-imagemin: Minified 5 images (saved 963 B - 3.8%)
> [15:17:13] images all files 24.13 kB
> [15:17:13] Finished 'images' after 965 ms
> app/elements/layer-height/layer-height.ts(30,28): error TS2304: Cannot
> find name 'PaperRadioGroup'.
> app/elements/layer-height/layer-height.ts(32,26): error TS2304: Cannot
> find name 'PaperInput'.
> app/elements/layer-height/layer-height.ts(35,53): error TS2304: Cannot
> find name 'PaperRadioGroup'.
> app/elements/layer-height/layer-height.ts(36,54): error TS2304: Cannot
> find name 'PaperInput'.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/DanielJoyce/microtome/issues/10#issuecomment-201549754
> 
> ## 
> 
> Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.

**Comment by DanielJoyce** [comment]
Most polymer elements don't have Typescript Ambient types defined, so you get these errors, but emit still works. It would be nice if they were warnings or something else instead. To me error should mean the build fails.
